### ISSUE TITLE
Plan the Database Structure

### ISSUE THREAD

**Issue by rvanooyen** [osbym/awsome-organics-gp2#1]
User Story:
As a client I want the data to be set up in a database with appropriate tables and data.

Acceptance Criteria:
When I access the database I have access to a User, Customer, Product, Category, and Order tables

When I access the User Table, I have access to User Name, Email, and password fields.

When I access the Customer Table I have access to Name, Email, Phone, Address, 

When I access the Product Table, I have access to Name, Category ID, Description, Quantity, and Price.
When I access the Category Table, I have access to the name, Description, and ID
When I access the Order Table, I have access to the User ID, Product ID, and Amount

**Comment by HacAtac** [comment]
nice job getting the connection to modules working
