### ISSUE TITLE
Research CSS Library 

### ISSUE THREAD

**Issue by osbym** [osbym/awsome-organics-gp2#2]
USER STORY
AS a developer I'd want to research CSS libraries so that I can utilize different styles in the client website

ACCEPTANCE CRITERIA
WHEN I research different CSS libraries I discover one that will fit within the scope of the client's website

**Comment by KumiYAM** [comment]
Note: at class of Nov 11,  suggestion  received from TA

These three  are currently in consideration 
*Materialized
*Bulma
*tailwind

**Comment by KumiYAM** [comment]
my opinion :  tailwind is  interesting 
point of interest : Ability to accessing tailwind using HTTP or js file.
                              Can be install as npm installer process.
                              It seems static landing page can be created.
