### ISSUE TITLE
Plan/Create landing page 

### ISSUE THREAD

**Issue by HacAtac** [osbym/awsome-organics-gp2#3]

**Comment by HacAtac** [comment]
User Story:
As a client I want to have a nice landing page when page loads

Acceptance Criteria:
When I land on webpage I see a polished interface that shows information about me and my products
So that when clients/users read they get a better understanding about where my idea and business came from.

**Comment by KumiYAM** [comment]
![Screen Shot 2021-11-16 at 0 30 49](https://user-images.githubusercontent.com/87912247/141935456-51e2763c-788d-4481-a3e8-c0f1c5efe122.png)

**Comment by KumiYAM** [comment]
Created html skelton for Landing Page.  This can be Demo purpose, or  start point of landing page.
*sign in button 
*log in button

*voice text accessibility friendly choice of html code

**Comment by HacAtac** [comment]
Hey Kumi, looks good. I went ahead and pushed an update for landing page. Just need someone to review it so I can merge it. On to the next one :)
